[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    {path = "script/target", access = "read-write"},
    {path = "broadcast", access = "read"},
    {path = "signature.txt", access = "read"},
]
remappings = [
    "forge-std=lib/forge-std/src",
    "@openzeppelin=lib/openzeppelin-contracts",
    "murky=lib/murky"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
